version: '3.8'

networks:
  ratecompare-network:
    driver: bridge

services:
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - API1_URL=http://api1:8002
      - API2_URL=http://api2:8003
      - API3_URL=http://api3:8004
      - EXCHANGE_URL=http://exchange-service:8001
    depends_on:
      - api1
      - api2
      - api3
      - exchange-service
    networks:
      - ratecompare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  exchange-service:
    build:
      context: .
      dockerfile: services/exchange-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO
      - API1_URL=http://api1:8002
      - API2_URL=http://api2:8003
      - API3_URL=http://api3:8004
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - ratecompare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api1:
    build:
      context: .
      dockerfile: services/api1/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - LOG_LEVEL=INFO
    networks:
      - ratecompare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api2:
    build:
      context: .
      dockerfile: services/api2/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - LOG_LEVEL=INFO
    networks:
      - ratecompare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api3:
    build:
      context: .
      dockerfile: services/api3/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - LOG_LEVEL=INFO
    networks:
      - ratecompare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
