version: '3.8'

services:
  ratecompare:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REQUEST_TIMEOUT=10
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
