version: '3.8'

services:
  exchange-service:
    build:
      context: ../../
      dockerfile: services/exchange-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - ratecompare-network

networks:
  ratecompare-network:
    driver: bridge
