version: '3.8'

services:
  api-gateway:
    build:
      context: ../../
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - ratecompare-network

networks:
  ratecompare-network:
    driver: bridge
