version: '3.8'

services:
  api3:
    build:
      context: ../../
      dockerfile: services/api3/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - ratecompare-network

networks:
  ratecompare-network:
    driver: bridge
